# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwitchUser',
            new_name='Gift',
        ),
    ]
